apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-storageclass
allowVolumeExpansion: true
provisioner: ebx.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3